In [81]:
    text=['dog like cat', #--->리뷰 1개 문서
         'dog dog fish river',#---
         'cat cute odd eye', #-----
         'cat dog human',
         'dog bark cut cry',
         'cat run dog run',
         'cat cat cat dog dog dog ',
         'dog eat cat cat dog']
    z_test=['dog cat dog cat']

In [82]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np

Encoding - CountVector(빈도 수)

In [83]:
cntvec=CountVectorizer()
ct= cntvec.fit(text)
ct_vec=ct.transform(text).toarray()
ct_vec # 8문장 수치화

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [84]:
print(ct.vocabulary_) #여기 voca 순서

{'dog': 5, 'like': 10, 'cat': 1, 'fish': 8, 'river': 12, 'cute': 4, 'odd': 11, 'eye': 7, 'human': 9, 'bark': 0, 'cut': 3, 'cry': 2, 'run': 13, 'eat': 6}


Encoding - TF-IDF(모든 문서에 공통적으로 들어있는 단어는 가중치 축소)

In [85]:
tfvec = TfidfVectorizer()
tf = tfvec.fit(text)
tf_vec=tf.transform(text).toarray()

In [86]:
np.round(tf_vec,3)

array([[0.   , 0.415, 0.   , 0.   , 0.   , 0.371, 0.   , 0.   , 0.   ,
        0.   , 0.831, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.534, 0.   , 0.   , 0.598,
        0.   , 0.   , 0.   , 0.598, 0.   ],
       [0.   , 0.277, 0.   , 0.   , 0.555, 0.   , 0.   , 0.555, 0.   ,
        0.   , 0.   , 0.555, 0.   , 0.   ],
       [0.   , 0.415, 0.   , 0.   , 0.   , 0.371, 0.   , 0.   , 0.   ,
        0.831, 0.   , 0.   , 0.   , 0.   ],
       [0.559, 0.   , 0.559, 0.559, 0.   , 0.25 , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.237, 0.   , 0.   , 0.   , 0.212, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.948],
       [0.   , 0.746, 0.   , 0.   , 0.   , 0.666, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.598, 0.   , 0.   , 0.   , 0.534, 0.598, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ]])

#### pratice-수치화-RNN으로 imdb감성분석

In [97]:
from keras.layers import LSTM, Input, Dense
from keras.models import Model
import numpy as np
from keras import backend as K
from numpy import argmax 

--TF-IDF 사용

In [88]:
#x_train 수치화
tfvec = TfidfVectorizer()
tf = tfvec.fit(text) #vocabulary만듦

tf_vec=tf.transform(text).toarray()
np.round(tf_vec,3)

array([[0.   , 0.415, 0.   , 0.   , 0.   , 0.371, 0.   , 0.   , 0.   ,
        0.   , 0.831, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.534, 0.   , 0.   , 0.598,
        0.   , 0.   , 0.   , 0.598, 0.   ],
       [0.   , 0.277, 0.   , 0.   , 0.555, 0.   , 0.   , 0.555, 0.   ,
        0.   , 0.   , 0.555, 0.   , 0.   ],
       [0.   , 0.415, 0.   , 0.   , 0.   , 0.371, 0.   , 0.   , 0.   ,
        0.831, 0.   , 0.   , 0.   , 0.   ],
       [0.559, 0.   , 0.559, 0.559, 0.   , 0.25 , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.237, 0.   , 0.   , 0.   , 0.212, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.948],
       [0.   , 0.746, 0.   , 0.   , 0.   , 0.666, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.598, 0.   , 0.   , 0.   , 0.534, 0.598, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ]])

In [89]:
#z_test 수치화
tf_vect=tf.transform(z_test).toarray()
np.round(tf_vect,3)

array([[0.   , 0.746, 0.   , 0.   , 0.   , 0.666, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ]])

In [90]:
tf_vect.shape

(1, 14)

In [101]:
x_train.shape

(8, 14, 1)

In [91]:
x_train=tf_vec.reshape(8, 14, 1)
y_train=np.random.choice([0, 1],[8, 1])
x_test=tf_vect.reshape(1, 14, 1)

In [92]:
np.round(x_train,3)

array([[[0.   ],
        [0.415],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.371],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.831],
        [0.   ],
        [0.   ],
        [0.   ]],

       [[0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.534],
        [0.   ],
        [0.   ],
        [0.598],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.598],
        [0.   ]],

       [[0.   ],
        [0.277],
        [0.   ],
        [0.   ],
        [0.555],
        [0.   ],
        [0.   ],
        [0.555],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.555],
        [0.   ],
        [0.   ]],

       [[0.   ],
        [0.415],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.371],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.831],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ]],

       [[0.559],
        [0.   ],
      

In [93]:
y_train.shape

(8, 1)

In [94]:
K.clear_session()

x_input=Input(batch_shape=(None, 14, 1))
x_hidden=LSTM(50)(x_input)
x_output=Dense(1,activation='sigmoid')(x_hidden)

model=Model(x_input, x_output)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 14, 1)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [95]:
model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(x_train, y_train, epochs=50, batch_size=1)

Epoch 1/50
8/8 [==============================] - 1s 118ms/step - loss: 0.6974
Epoch 2/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6935
Epoch 3/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6909
Epoch 4/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6926
Epoch 5/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6863
Epoch 6/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6842
Epoch 7/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6825
Epoch 8/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6804
Epoch 9/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6778
Epoch 10/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6733
Epoch 11/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6891
Epoch 12/50
8/8 [==============================] - 0s 7ms/step - loss: 0.6702
Epoch 13/50
8/8 [==============================] - 0s 7ms/step - loss: 

In [99]:
model.predict(x_test, batch_size=1)

array([[0.6156859]], dtype=float32)

In [100]:
a=model.predict(x_test, batch_size=1)
a.argmax()

0