In [1]:
import numpy as np
r=np.array([0.7, 0.8])

In [2]:
m1=r/r.sum()

단순 표준화

In [3]:
m1

array([0.46666667, 0.53333333])

In [4]:
np.sum(m1)

1.0

In [8]:
m1[1]-m1[0]

0.06666666666666671

softmax, 비선형

In [9]:
m2=np.exp(r)/np.sum(np.exp(r))
m2

array([0.47502081, 0.52497919])

In [7]:
np.exp(r)/np.exp(r)

array([1.26280234, 1.30560517])

In [13]:
m3=np.exp(r/.2)/np.sum(np.exp(r/.2))
m3 # B라는 값을 지수에 도입하면 조금 더 유연하게 격차를 크게 (효과가 큰)하는 방향으로 사용할 수 있다.

array([0.37754067, 0.62245933])

keras에서도 쓸 수 있을까?

In [18]:
np.random.multinomial(1, [1/6,1/6,1/6,1/6,1/6,1/6],10) #주사위 던지기 (다항 분포)
                   # 주사위 갯수                 주사위 던지는 횟수

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [23]:
np.random.multinomial(10, [0.1,0.3,0.1,0.2,0.1,0.2],10)#찌그러진 주사위

array([[0, 4, 0, 3, 1, 2],
       [1, 1, 2, 5, 0, 1],
       [1, 3, 0, 0, 2, 4],
       [0, 2, 0, 6, 1, 1],
       [1, 4, 0, 3, 0, 2],
       [0, 3, 0, 4, 1, 2],
       [0, 4, 0, 3, 0, 3],
       [0, 1, 2, 3, 2, 2],
       [1, 5, 0, 2, 0, 2],
       [0, 1, 0, 4, 3, 2]])

In [24]:
np.random.multinomial(10, [0.1,0.3,0.1,0.2,0.1,1000],10)
#마지막 값은 1을 넘어도 통과되네-> 1-x 이런 식으로 진행되나봐 (1000의 의미가 사라짐)

array([[0, 2, 0, 3, 1, 4],
       [1, 4, 0, 3, 1, 1],
       [2, 5, 0, 0, 2, 1],
       [1, 1, 2, 3, 1, 2],
       [0, 2, 2, 1, 2, 3],
       [1, 5, 0, 0, 1, 3],
       [2, 2, 1, 4, 0, 1],
       [1, 3, 0, 5, 1, 0],
       [0, 2, 3, 1, 2, 2],
       [4, 2, 0, 1, 2, 1]])