In [2]:
from sklearn.datasets import load_wine

In [3]:
dataset=load_wine()
dataset

      #data가 dict형태로 되어 있다 --> data : feature, target = target value 들어가있는 것 확인--->key값을 정해주자

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [4]:
dataset['data']

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [7]:
dataset['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [12]:
from pprint import pprint
pprint(dataset['DESCR'])

('.. _wine_dataset:\n'
 '\n'
 'Wine recognition dataset\n'
 '------------------------\n'
 '\n'
 '**Data Set Characteristics:**\n'
 '\n'
 '    :Number of Instances: 178 (50 in each of three classes)\n'
 '    :Number of Attributes: 13 numeric, predictive attributes and the class\n'
 '    :Attribute Information:\n'
 ' \t\t- Alcohol\n'
 ' \t\t- Malic acid\n'
 ' \t\t- Ash\n'
 '\t\t- Alcalinity of ash  \n'
 ' \t\t- Magnesium\n'
 '\t\t- Total phenols\n'
 ' \t\t- Flavanoids\n'
 ' \t\t- Nonflavanoid phenols\n'
 ' \t\t- Proanthocyanins\n'
 '\t\t- Color intensity\n'
 ' \t\t- Hue\n'
 ' \t\t- OD280/OD315 of diluted wines\n'
 ' \t\t- Proline\n'
 '\n'
 '    - class:\n'
 '            - class_0\n'
 '            - class_1\n'
 '            - class_2\n'
 '\t\t\n'
 '    :Summary Statistics:\n'
 '    \n'
 '    ============================= ==== ===== ======= =====\n'
 '                                   Min   Max   Mean     SD\n'
 '    ============================= ==== ===== ======= =====\n'
 '    Alcohol:

In [14]:
len(dataset['feature_names'])

13

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [16]:
type(dataset.data)

numpy.ndarray

In [17]:
import pandas as pd

C:\ProgramData\Anaconda3\envs\finance\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\envs\finance\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [30]:
data_df = pd.DataFrame(dataset.data, columns = dataset.feature_names)
data_df.head()   #target value

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [45]:
X,y=dataset['data'],dataset['target']

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [47]:
model_logistic =LogisticRegression(multi_class ='multinomial',
                                  solver='lbfgs',
                                  C=0.2).fit(X_train,y_train)  #overfitting 막으려 규제 강하게 줌.

C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [48]:
(model_logistic.coef_).shape  #각 각에 대하여 13개의 feature값

(3, 13)

In [49]:
model_logistic.intercept_

array([-0.02007043,  0.05652358, -0.03645315])

In [50]:
model_logistic.score(X_train,y_train)  #차이가 좀 나지만 overfitting 막기 위함     100개 중 몇개를 맞추었는가?""

0.9624060150375939

In [51]:
predict_test= model_logistic.predict(X_test)
predict_test

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0, 2,
       1])

In [60]:
y_test

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2,
       1])

In [61]:
import numpy as np

In [62]:
np.mean(np.equal(y_test,predict_test).astype(int))         #equal함수는 서로 같을 때는 true 다르면 false를 뽑음 -->정확도도 쟤보자(astype)

0.9777777777777777

In [63]:
np.cast(True, 1)

TypeError: '_typedict' object is not callable