# Numpy(수치해석용 패키지) 

In [57]:
import numpy as np

In [2]:
data = np.array([1,2,3,4])

In [3]:
data

array([1, 2, 3, 4])

In [4]:
type(data)

numpy.ndarray

In [5]:
data_2 = np.zeros(10) #크기를 
data_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
data3 = np.ones([5,5]) #몇행 몇열로 만들거냐

In [7]:
data3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
data4 = np.arange(0,10,1) #기억 for i in 'range()'
data4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
data_5 = np.linspace(0,10,5) #(시작, 끝(포함), 갯수) 같은 간격으로 만든것이다.
data_5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
data_log = np.logspace(1,10,5) #과학적인 표긱법으로 간격으로 나눈것이다.
data_log

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [11]:
data_6 =np.random.randint(1,10,size=(2,10)) # (시작,끝,사이즈) 시작과 끝 값에서 랜덤으로 값을 리턴
data_6

array([[3, 5, 6, 3, 1, 5, 5, 4, 7, 9],
       [8, 5, 6, 1, 8, 4, 6, 1, 1, 4]])

- data_6과 동일한 size의 0 array를 만들고 싶다면?

In [20]:
data_zero = np.zeros_like(data_6) #(배열)을 입력해야 동일한 크기의 0배열을 생성
data_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
data_one = np.ones_like(data_zero) #(배열)을 입력해야 동일한 크기의 1배열을생성
data_one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

###  배열 파악

In [22]:
data_one.ndim #배열의 차원

2

In [23]:
data_one.shape #배열의 shape

(2, 10)

In [24]:
data_one.dtype

dtype('int32')

In [26]:
#리스트와 비교
data_list=[1,2.0,'hello'] #다문화가정

data_array = np.array([1,2.0,'hello']) #단일민족
data_array

array(['1', '2.0', 'hello'], dtype='<U32')

In [28]:
data_array.dtype

dtype('<U32')

In [29]:
data_array[0]


'1'

In [33]:
data_array2 = np.array([1,2,3])

data_array2.astype('f') #배열의 데이터의 형변환

array([1., 2., 3.], dtype=float32)

In [34]:
data_array2.astype('O') #주의 문자열 : 'O'(알파벳)

array([1, 2, 3], dtype=object)

### Numpy의 강점

- 1개의 데이터 : Vector = 1차원 배열 
- 여러개의 데이터 : Matrix = 2차원 배열

1. 벡터화 연산이 가능하다.
2. 변환이 쉽다
3. 조건식으로 데이터 지정하기가 쉽다.
4. 계산이 빠르다
5. 슬라이싱이 가능하다

In [54]:
#리스트와 비교
a = [1,2,3]

c = a*3 #+은 불가능
c 

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [47]:
x = np.array(a)
y,z = x+3,x*3
y,z

(array([4, 5, 6]), array([3, 6, 9]))

In [48]:
x + y

array([5, 7, 9])

In [59]:
x*y

array([ 4, 10, 18])

In [62]:
data1 = np.array([1,2,3,4])
data2 = np.array([4,1,0,0])
data1+data2, data1*data2

(array([5, 3, 3, 4]), array([4, 2, 0, 0]))

In [92]:
data1.shape

(4,)

In [101]:
data = np.array([[1,2,3,4],[4,1,0,0]])

In [104]:
data.shape

(2, 4)

In [94]:
data = np.array(1) #1행 1열 스칼라
data.shape #n행 1열은 벡트/ n행 m열은 메트릭스

()

In [65]:
data1@data2 #행렬 곱

6

In [72]:
data3 = np.array([[1,0],[2,0],[3,0]])
data4 = np.array([[1,2],[3,4],[0,0]])
#data3*data4
#data@data4 오류로 계산불가

In [76]:
data5 = np.array([[1,2],[3,0]])
data6 = np.array([[1,0,1,0],[2,0,1,1]])
data5@data6

array([[5, 0, 3, 2],
       [3, 0, 3, 0]])

In [79]:
data1 = np.array([1,2,3,4])
data2 = np.array([4,1,0,0])
data1+data2, data1*data2
data1@data2

6

In [80]:
data6 = np.array([[1,0,1,0],[2,0,1,1]])
data6

array([[1, 0, 1, 0],
       [2, 0, 1, 1]])

- data6을 전치시키고 싶다면? (대각선 회전)

In [81]:
data6.T

array([[1, 2],
       [0, 0],
       [1, 1],
       [0, 1]])

In [89]:
data7 = np.arange(10) #for i in 'range'
data7.T,data7

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

- 전치가 아니라 내가 원하는 shape으로 바꾸고 싶다면?

In [88]:
data7.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- data7에서 짝수만 뽑아내고 싶다면?

In [91]:
data7[data7%2 ==0] #조건식으로 지정 가능

array([0, 2, 4, 6, 8])