In [125]:
import pandas as pd
import numpy as np
import tensorflow as tf

saveDir='./Saver/predictStock(reg).save'
saveFile=saveDir+'/save'

In [126]:
KT=pd.read_csv('./stockData/030200.csv',index_col=0, parse_dates=True)
                                     # 0번째 열 인덱스화  index 날짜를 파싱할까?
KT=KT.sort_index()
KT=KT.dropna()
KT=KT/10000

In [127]:
KT.tail()

open   high    low  close   volume
date                                           
2019-06-19  2.860  2.870  2.845  2.850  35.9243
2019-06-20  2.860  2.860  2.830  2.840  50.5181
2019-06-21  2.835  2.855  2.820  2.820  50.7850
2019-06-24  2.835  2.860  2.825  2.835  39.8871
2019-06-25  2.840  2.850  2.825  2.825  19.4735

In [128]:
KT['kta120'] = KT['close'].rolling(window=20).mean()      # window=120: 120일 이동평균  rolloing: 데이터 아래로 sliding    mean: 평균
KT['kta240'] = KT['close'].rolling(window=60).mean()      # 240일 이동평균


In [129]:
KT['last close']=KT['close'].shift(-1)
KT.tail()

open   high    low  close   volume   kta120    kta240  last close
date                                                                          
2019-06-19  2.860  2.870  2.845  2.850  35.9243  2.79950  2.772917       2.840
2019-06-20  2.860  2.860  2.830  2.840  50.5181  2.80525  2.773833       2.820
2019-06-21  2.835  2.855  2.820  2.820  50.7850  2.81075  2.774833       2.835
2019-06-24  2.835  2.860  2.825  2.835  39.8871  2.81550  2.775917       2.825
2019-06-25  2.840  2.850  2.825  2.825  19.4735  2.82000  2.776667         NaN

In [121]:
KT['class']= 0.0
KT.loc[KT['last close']> KT['close'], 'class']=1
KT=KT.drop('volume',axis=1)

In [132]:
KT=KT.sample(frac=1)
KT

open   high    low  close    volume   kta120    kta240  \
date                                                                  
2014-02-25  2.920  2.995  2.920  2.985  109.8742  3.00950  3.079750   
2017-10-25  2.980  2.995  2.960  2.960   58.6427  2.94500  3.133333   
2016-08-01  3.220  3.265  3.200  3.260   85.5499  3.08725  3.090333   
2017-06-15  3.160  3.215  3.150  3.165   40.6306  3.19675  3.197000   
2012-03-29  3.215  3.220  3.160  3.170  150.3175  3.23700  3.292583   
2012-07-26  3.285  3.325  3.275  3.295   85.1550  3.19450  2.996250   
2019-05-08  2.780  2.865  2.775  2.845  214.4187  2.75350  2.784750   
2016-05-26  3.200  3.225  3.175  3.195   46.0606  3.15475  3.021833   
2012-10-22  3.480  3.500  3.460  3.495   46.9215  3.51700  3.451167   
2013-12-10  3.020  3.030  2.990  2.995  141.4931  3.22925  3.440667   
2013-04-01  3.530  3.530  3.495  3.515   25.6134  3.61425  3.641083   
2015-10-23  3.065  3.085  3.055  3.060   52.5196  3.03600  2.981583   
2015-02-17  2.945  3.015  2.930  3.000  150.3690  2.96225  3.090500   
2018-05-21  2.735  2.750  2.730  2.735   23.1379  2.73050  2.746333   
2012-03-05  3.290  3.310  3.250  3.265   56.7021  3.25375  3.432417   
2014-12-11  3.130  3.155  3.110  3.135   80.5094  3.24525  3.303500   
2012-10-24  3.515  3.695  3.515  3.670  259.2670  3.51775  3.461167   
2015-03-23  2.970  2.975  2.920  2.945   97.1941  3.00625  3.017917   
2019-05-22  2.735  2.750  2.720  2.725   43.6066  2.77175  2.773583   
2012-05-07  2.865  3.070  2.855  3.050  307.0549  3.00400  3.150167   
2016-08-22  3.200  3.210  3.120  3.130   62.3582  3.21550  3.102667   
2012-09-17  3.590  3.600  3.500  3.545  193.8604  3.51100  3.304917   
2017-04-12  3.135  3.145  3.095  3.115   65.6027  3.24050  3.097667   
2013-05-20  4.055  4.090  3.975  4.045   98.2802  3.81025  3.649583   
2013-06-05  3.800  3.820  3.745  3.765  111.6147  3.95175  3.718917   
2017-03-29  3.255  3.255  3.175  3.190   90.0909  3.20825  3.049083   
2015-03-27  2.925  2.955  2.920  2.945   89.8554  2.98250  2.999167   
2011-08-11  3.385  3.485  3.385  3.420  310.0498  3.85725  3.840417   
2012-07-20  3.190  3.190  3.090  3.130  182.2122  3.12000  2.976583   
2012-04-12  3.115  3.120  3.050  3.090   80.9508  3.17425  3.246250   
...           ...    ...    ...    ...       ...      ...       ...   
2014-03-11  2.870  2.885  2.835  2.860  113.4044  2.96275  3.045833   
2011-09-06  3.620  3.690  3.585  3.660  104.6547  3.65750  3.819500   
2018-05-30  2.720  2.725  2.695  2.705   56.1031  2.73275  2.737333   
2013-05-15  4.080  4.105  4.000  4.080  115.7268  3.76600  3.632083   
2013-08-26  3.490  3.500  3.465  3.480   47.5080  3.56850  3.614000   
2016-04-26  3.020  3.035  3.005  3.020   53.2562  3.02450  2.910333   
2015-04-21  2.960  2.965  2.935  2.935   64.6149  2.92800  2.964833   
2015-02-27  3.045  3.080  3.025  3.060  340.2100  2.96725  3.068500   
2012-12-21  3.850  3.885  3.845  3.855  190.0588  3.81875  3.719167   
2016-12-27  3.020  3.030  3.015  3.020   54.4322  2.99300  3.105917   
2019-04-09  2.750  2.760  2.720  2.720   60.2810  2.76725  2.833583   
2015-02-12  2.935  2.955  2.905  2.940  103.2457  2.96825  3.107583   
2013-10-24  3.575  3.575  3.535  3.570  151.2975  3.60450  3.599583   
2012-08-02  3.210  3.260  3.180  3.220   56.6383  3.23075  3.018667   
2019-05-20  2.790  2.800  2.745  2.745  112.1578  2.77425  2.777167   
2014-06-05  2.970  2.980  2.915  2.945   89.1429  3.15150  3.090167   
2018-02-06  2.920  2.930  2.875  2.890  196.5078  2.98125  3.009167   
2016-05-10  3.180  3.210  3.180  3.185   56.1686  3.07900  2.956917   
2012-06-19  2.850  2.875  2.845  2.860   50.1686  2.84800  2.982250   
2013-07-08  3.615  3.660  3.555  3.560   56.8556  3.64250  3.748000   
2018-06-01  2.715  2.715  2.690  2.700   25.2463  2.72975  2.735083   
2012-11-02  3.715  3.745  3.685  3.705   89.5324  3.57825  3.516083   
2014-04-23  3.200  3.280  3.180  3.265  248.9741  3.09575  3.009333   
2018-09-13  2.900  2.920  2.885  2.88

In [87]:
len(KT.loc[KT['class']==0.0])

1110

In [88]:
testX = np.array(KT.iloc[-1:, 0:6])

KT=KT.dropna()

#X_Input=np.array(KT.iloc[:, 0:4])
#X_Input.shape

#Y_output=np.array(KT.loc[:, 'class']).reshape(-1,1)
#Y_output

inputX = np.array(KT.iloc[:1500, 0:6])
outputY = np.array(KT.iloc[:1500, 7]).reshape(-1,1)

testX = np.array(KT.iloc[1500:, 0:6])
testY = np.array(KT.iloc[1500:, 7]).reshape(-1,1)

In [89]:
outputY

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [90]:
InPut=6
We=10
OutPut=1

In [91]:
tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[None,InPut],name='x')
y = tf.placeholder(tf.float32, shape=[None,OutPut], name='y')

W1 = tf.Variable(tf.truncated_normal([InPut, We]), dtype=tf.float32, name= 'W1')
B1 = tf.Variable(tf.zeros([We]),dtype=tf.float32, name= 'B1')
H1 = tf.nn.relu(tf.add(tf.matmul(x,W1), B1, name= 'H1'))

#W2 = tf.Variable(tf.truncated_normal([We,We1]), dtype=tf.float32, name= 'W2')
#B2 = tf.Variable(tf.zeros(We1),dtype=tf.float32, name= 'B2')
#H2 = tf.nn.sigmoid(tf.matmul(H1, W2) +B2, name= 'H2')
    
W0 = tf.Variable(tf.truncated_normal([We, OutPut]), dtype=tf.float32, name='W0')
B0 = tf.Variable(tf.zeros([OutPut]),dtype=tf.float32, name='B0')

lstY = tf.nn.sigmoid(tf.add(tf.matmul(H1,W0),B0, name='lstY'))

cost = tf.reduce_mean(tf.square(tf.subtract(lstY, y)))

learning_rate = 1
alpha = tf.placeholder(tf.float32, shape=(), name='alpha')
optimizer = tf.train.GradientDescentOptimizer(alpha)
train = optimizer.minimize(cost)


#saver=tf.train.Saver()

In [92]:
nBatchCnt= 5
nBatchSize= int(inputX.shape[0] / nBatchCnt)

sess = tf.Session()
sess.run(tf.global_variables_initializer()) #그래프 실행

#if tf.train.checkpoint_exists(saveDir):
#    saver.restore(sess, saveFile)

In [93]:
for i in range(10000):
    # Mini-batch 방식으로 학습한다
    for n in range(nBatchCnt):
        # input 데이터를 Mini-batch 크기에 맞게 자른다
        nFrom = n * nBatchSize
        nTo = n * nBatchSize + nBatchSize

        # 마지막 루프이면 nTo는 input 데이터의 끝까지.
        if n == nBatchCnt - 1:
            nTo = inputX.shape[0]
            
        bx = inputX[nFrom : nTo]
        by = outputY[nFrom : nTo]
        
        _, xcost = sess.run([train, cost], feed_dict={x: bx, y: by, alpha:0.001})
    
    if i % 1000 == 0:
        print('cost = %.6f' % xcost)
           
# 학습 결과를 저장해 둔다
#saver.save(sess, saveFile)

cost = 0.362317
cost = 0.247302
cost = 0.247099
cost = 0.246909
cost = 0.246731
cost = 0.246563
cost = 0.246405
cost = 0.246255
cost = 0.246112
cost = 0.245977


In [94]:
testX

array([[4.06      , 4.12      , 4.035     , 4.085     , 3.74075   ,
        3.62325   ],
       [3.085     , 3.1       , 3.065     , 3.085     , 3.35025   ,
        3.40316667],
       [3.56      , 3.575     , 3.525     , 3.545     , 3.58975   ,
        3.64466667],
       ...,
       [2.855     , 2.875     , 2.85      , 2.85      , 2.924     ,
        2.97091667],
       [3.005     , 3.01      , 2.98      , 2.98      , 3.0465    ,
        3.00266667],
       [3.02      , 3.055     , 2.99      , 3.025     , 3.14775   ,
        3.07125   ]])

In [95]:
#yHat[np.where(yHat>0.5)]=1
#yhat[np.where(yHat<0.5)]=0
yHat=sess.run(lstY, feed_dict={x: testX})
print(yHat)
yHat=np.array([1 if x > 0.5 else 0 for x in yHat]).reshape(-1,1)

[[0.44877407]
 [0.39616567]
 [0.43528563]
 [0.42840156]
 [0.4179409 ]
 [0.43924797]
 [0.42881912]
 [0.3747573 ]
 [0.48474008]
 [0.44932604]
 [0.466413  ]
 [0.4628713 ]
 [0.44873223]
 [0.45087698]
 [0.42398685]
 [0.4529501 ]
 [0.46418384]
 [0.3999043 ]
 [0.43699303]
 [0.44864303]
 [0.4604687 ]
 [0.47666875]
 [0.47237056]
 [0.4715705 ]
 [0.5020994 ]
 [0.43665546]
 [0.4807098 ]
 [0.38502878]
 [0.53054667]
 [0.44694164]
 [0.44164172]
 [0.46115407]
 [0.38163167]
 [0.4087857 ]
 [0.42627794]
 [0.3907157 ]
 [0.48404533]
 [0.45167473]
 [0.36598498]
 [0.44465026]
 [0.43615156]
 [0.47959742]
 [0.42066193]
 [0.45284227]
 [0.3540613 ]
 [0.4238388 ]
 [0.40953565]
 [0.39168972]
 [0.4214133 ]
 [0.4443823 ]
 [0.42547816]
 [0.40089786]
 [0.40979362]
 [0.4670949 ]
 [0.48125416]
 [0.42984352]
 [0.45289353]
 [0.47818598]
 [0.44758487]
 [0.44902804]
 [0.45123938]
 [0.4353618 ]
 [0.49174938]
 [0.47346324]
 [0.38144124]
 [0.44965747]
 [0.38732776]
 [0.3979826 ]
 [0.4448473 ]
 [0.47157174]
 [0.43653196]
 [0.46

In [96]:
yHat

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [97]:
accuracy=(testY==yHat).sum() / len(testX)

print('Accuracy = %.4f' % accuracy)

Accuracy = 0.5477


In [98]:
yHat=sess.run(lstY, feed_dict = {x : inputX})
print("\ny-추정치 = \n",accuracy)


y-추정치 = 
 0.5477272727272727


In [133]:
# XOR 예시
import tensorflow as tf
import pandas as pd
import numpy as np

In [134]:
sm = pd.read_csv('./stockData/005930.csv', index_col=0, parse_dates=True)
sm = sm.sort_index() # 날짜 순으로 정렬한다
sm = sm.dropna()
sm=sm/10000 #스케일을 줄여서 

In [135]:
sm.tail()

open   high    low  close     volume
date                                             
2019-06-19  4.545  4.545  4.500  4.535  1041.7690
2019-06-20  4.485  4.550  4.485  4.550   714.7785
2019-06-21  4.575  4.580  4.520  4.570   945.4913
2019-06-24  4.520  4.580  4.520  4.550   608.5066
2019-06-25  4.520  4.580  4.520  4.545   412.0726

In [136]:
sm['next close'] = sm['close'].shift(-1)

In [137]:
sm.tail() #옆에 새로 생김!

open   high    low  close     volume  next close
date                                                         
2019-06-19  4.545  4.545  4.500  4.535  1041.7690       4.550
2019-06-20  4.485  4.550  4.485  4.550   714.7785       4.570
2019-06-21  4.575  4.580  4.520  4.570   945.4913       4.550
2019-06-24  4.520  4.580  4.520  4.550   608.5066       4.545
2019-06-25  4.520  4.580  4.520  4.545   412.0726         NaN

In [ ]:
testX = np.array(sm.iloc[-1:, 0:4]) # 맨 아래 줄 애들 가리킴, 행과 열로 원하는 애들 뽑아옴
testX

In [ ]:
sm = sm.dropna() #마지막 날 nan값 없앰

In [ ]:
inputX = np.array(sm.iloc[:,0:4])# input 데이터-> (1999, 4) 구조로 바꿈
outputY =np.array(sm.loc[:, 'next close']).reshape(-1,1)  # 1차원 구조로 맞춰주기 위해서 reshape해줌
                            # 이름으로 바로 지정

In [ ]:
outputY #2차원 구조 이면서도 하나씩 정렬됨.-------------->inputX와 outY 정리 끝!

In [ ]:
nInput = 4      # input layer의 neuron 개수
nHidden = 80     # hidden layer의 neuron 개수
nOutput = 1     # output layer의 neuron 개수

In [ ]:
# 그래프를 생성한다
tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[None, nInput], name='x')
y = tf.placeholder(tf.float32, shape=[None, nOutput], name='y')

In [ ]:
#Hidden 1
# hidden layer의 Weight (Wh)와 Bias (Bh)
W1 = tf.Variable(tf.truncated_normal([nInput, nHidden]), dtype=tf.float32, name='W1')
B1 = tf.Variable(tf.zeros(nHidden), dtype=tf.float32, name='B1')

#Hidden 2
#hidden_layer가 많으면 sigmoid 말고 relu로! sigmoid는 1과 0으로 구분하기 때문에 가격값을 찾는 것에 적합하지 않다.
W2 = tf.Variable(tf.truncated_normal([nHidden, nHidden]), dtype=tf.float32, name='W2')
B2 = tf.Variable(tf.zeros(nHidden), dtype=tf.float32, name='B2')

# output layer의 Weight (Wo)와 Bias (Bo)
Wo = tf.Variable(tf.truncated_normal([nHidden, nOutput]), dtype=tf.float32, name='Wo')
Bo = tf.Variable(tf.zeros(nOutput), dtype=tf.float32, name='Bo')

H1 = tf.nn.relu(tf.matmul(x, W1) + B1, name='H1') 
H2 = tf.nn.relu(tf.matmul(H1, W2) + B2, name='H2')


# Output layer의 출력값. activation function은 sigmoid
predY = tf.nn.sigmoid(tf.add(tf.matmul(H2, Wo), Bo, name='predY'))

# Cost function 정의. cross-entropy 사용
cost = tf.reduce_mean(tf.square(tf.subtract(predY, y)))

# 학습
optimizer = tf.train.AdamOptimizer(0.05)
train = optimizer.minimize(cost)

alpha=tf.placeholder(tf.float32, shape=(), name='alpha')

In [ ]:
# 그래프를 실행한다
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for i in range(10000):
    _, xcost = sess.run([train, cost], feed_dict={x: inputX, y: outputY, alpha:0.01})
    
    if i % 1000 == 0:
        print('cost = %.4f' % xcost)

In [ ]:
yHat = (sess.run(predY, feed_dict={x: testX}))*10000
print('\ny=추정치 = \n', yHat)

In [102]:
print("\ny-추정치 = \n", yHat)

# Weight, Bias의 최종값을 확인해 본다
rW1, rB1, rWo, rBo = sess.run([W1, B1, Wo, Bo])

print("\nW1 = \n", rW1)
print("\nB1 = \n", rB1)
print("\nWo = \n", rWo)
print("\nBo = \n", rBo)
sess.close()



y-추정치 = 
 [[0.4476745 ]
 [0.46764812]
 [0.46374407]
 ...
 [0.41108844]
 [0.4735971 ]
 [0.4827249 ]]


NameError: name 'Wo' is not defined

In [106]:
sm=sm.sample(frac=1)
sm.head()

AttributeError: 'function' object has no attribute 'sample'