In [35]:
import nltk
import math
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [36]:
statements=[
    'ruled india',
    'Chalukyas ruled Badami',
    'So many kingdoms ruled India',

    'Lalbagh is a botanical garden in India'
]

In [37]:
vec=TfidfVectorizer()
tfidf=vec.fit_transform(statements).toarray()#########################d암기!!
#fit->voca만들기, transrorm:

In [38]:
#cosine 거리

def cos_distance(x,y):
    return np.dot(x,y) / (np.linalg.norm(x) * np.linalg.norm(y))

In [39]:
print('문서(1)-(3) : ', cos_distance(tfidf[0],tfidf[2]))
print('문서(3)-(4) : ', cos_distance(tfidf[2],tfidf[3]))

문서(1)-(3) :  0.4621617116387793
문서(3)-(4) :  0.08970162937905388


In [40]:
cosine_similarity([tfidf[2]],[tfidf[3]])

array([[0.08970163]])

In [43]:
tfidf[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.70710678, 0.        ])

In [44]:
tfidf[1]

array([0.64450299, 0.        , 0.64450299, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.41137791, 0.        ])